# Site settings
title: kiko.rb my ruby backups!
email: kikorb@gmail.com
description: >
  This is my github site where I intend to post the changes I am making to
  my projects, the things I think might be usefull for anyone and that stuff
  I will like to read 5 years from now.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://kikorb.com" # the base hostname & protocol for your site

twitter_username: kikoruiz
github_username:  kikorb

author :
  name : Francisco Ruiz Benito
  email : kikorb@gmail.com
  github : kikorb
  twitter : kikoruiz

# Build settings
markdown: kramdown
